---
galaxy_info:
  author: Daniel Gryniewicz
  description: Installs Ceph NFS Gateway
  license: Apache
  min_ansible_version: 2.3
  platforms:
    - name: Ubuntu
      versions:
        - xenial
    - name: EL
      versions:
        - 7
    - name: opensuse
      versions:
        - 42.3
  categories:
    - system
dependencies: []
