---
- name: check ntp installation on redhat or suse
  command: rpm -q ntp
  args:
    warn: no
  register: ntp_pkg_query
  ignore_errors: true
  check_mode: no
  changed_when: false
  when:
    - ansible_os_family in ['RedHat', 'Suse']

- name: install ntp on redhat or suse
  package:
    name: ntp
    state: present
