---
- name: configure debian custom repository
  apt_repository:
    repo: "deb {{ ceph_custom_repo }} {{ ansible_lsb.codename }} main"
    state: present
    update_cache: no
  register: add_debian_apt_repo
