---
- name: configure openSUSE ceph OBS repository
  zypper_repository:
    name: "OBS:filesystems:ceph"
    state: present
    uri: "{{ ceph_obs_repo }}"
    auto_import_keys: yes
    autorefresh: yes
